SUPABASE_URL = "https://aqraijoagwppwosjadil.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
SUPABASE_DB_URL = "postgresql://postgres:b0QfVwycH3Il4fYw@db.aqraijoagwppwosjadil.supabase.co:5432/postgres"